# Quick Start
# $ xhost local:root
# $ docker compose -f compose.gazebo.yaml -f compose.gazebo.husarnet.yaml up

services:
  rosbot_xl:
    network_mode: service:husarnet-gazebo
    volumes:
      - ./secret/dds-config.xml:/dds-config.xml
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///dds-config.xml

  nav2:
    network_mode: service:husarnet-gazebo
    volumes:
      - ./secret/dds-config.xml:/dds-config.xml
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///dds-config.xml

  husarnet-gazebo:
    image: husarnet/husarnet
    volumes:
      - /var/lib/husarnet
      - ./secret/id_gazebo:/var/lib/husarnet/id
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0 
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - HOSTNAME=gazebo
      - JOINCODE=${HUSARNET_JOINCODE}

# Needed if running all compose.*.yaml files on the same host. Thanks to those lines a new subnet for this compose file is created
networks:
  default:
    name: net_gazebo
    driver: bridge