# Quick Start
# $ xhost local:root
# $ docker compose -f compose.ds.yaml  up

services:
  talker:
    build: .
    network_mode: service:husarnet-ds
    volumes: 
      - ./secret/dds-config.server.xml:/dds-config.xml
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTRTPS_DEFAULT_PROFILES_FILE=/dds-config.xml
    command: ros2 run demo_nodes_cpp talker

  husarnet-ds:
    image: husarnet/husarnet
    volumes:
      - /var/lib/husarnet
      - ./secret/id_discovery_server:/var/lib/husarnet/id
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0 
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - HOSTNAME=discovery_server
      - JOINCODE=${HUSARNET_JOINCODE}