# Quick Start
# $ xhost local:root
# $ docker compose -f compose.pc.yaml up

services:
  rviz:
    image: husarion/rviz2:galactic
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/slam.rviz:/root/.rviz2/default.rviz
    environment:
      - DISPLAY