# Quick Start
# $ xhost local:root
# $ docker compose -f compose.rosds.yaml -f compose.rosds.husarnet.yaml up

services:
  rosbot_xl:
    network_mode: service:husarnet-rosds
    volumes:
      - ./secret/dds-config.xml:/dds-config.xml
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTRTPS_DEFAULT_PROFILES_FILE=/dds-config.xml

  nav2:
    network_mode: service:husarnet-rosds
    volumes:
      - ./secret/dds-config.xml:/dds-config.xml
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTRTPS_DEFAULT_PROFILES_FILE=/dds-config.xml

  husarnet-rosds:
    image: husarnet/husarnet
    volumes:
      - /var/lib/husarnet
      - ./secret/id_rosds:/var/lib/husarnet/id
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0 
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - HOSTNAME=rosds
      - JOINCODE=${HUSARNET_JOINCODE}