# Quick Start
# $ xhost local:root
# $ docker compose -f compose.pc.yaml -f compose.pc.husarnet.yaml up

services:
  rviz:
    network_mode: service:husarnet-pc
    volumes: 
      - ./secret/dds-config.xml:/dds-config.xml
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTRTPS_DEFAULT_PROFILES_FILE=/dds-config.xml

  husarnet-pc:
    image: husarnet/husarnet
    volumes:
      - /var/lib/husarnet
      - ./secret/id_rviz2:/var/lib/husarnet/id
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0 
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - HOSTNAME=rviz2
      - JOINCODE=${HUSARNET_JOINCODE}